// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function DecryptFileAES256GCM(password: string, inputFile: string, outputPath: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3311871556, password, inputFile, outputPath) as any;
    return $resultPromise;
}

export function EncryptFileAES256GCM(password: string, inputPath: string, outputPath: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1211961388, password, inputPath, outputPath) as any;
    return $resultPromise;
}

export function GetFilePath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3837636509) as any;
    return $resultPromise;
}

export function GetOutputPath(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3194427022) as any;
    return $resultPromise;
}
