// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class AppResponse {
    "Message": string;
    "Status": number;

    /** Creates a new AppResponse instance. */
    constructor($$source: Partial<AppResponse> = {}) {
        if (!("Message" in $$source)) {
            this["Message"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): AppResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppResponse($$parsedSource as Partial<AppResponse>);
    }
}
